# Generated by Django 4.1.3 on 2022-11-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_pressure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
